### ISSUE TITLE
SEO: Metadata tags for neater embeds

### ISSUE THREAD

**Issue by Vyvy-vi** [MetaFam/metagame-wiki#234]
## Description
Currently, the metagame wiki makes a terrible embed on discord, with just a title(and most probably in other social platforms as well).
We could add some Meta tags for some form of SEO, and esp. for having neatly embedded links that can actually attract people more, and perhaps give more context.

The current embeds-
![current link embed only has a title](https://media.discordapp.net/attachments/782054676546846752/846841123280125952/Screenshot_2021-05-26_at_1.31.48_AM.png)

As you can see above - the current metagame links don't look so cool on discord. (The link posted below is a site that contains some of the said opengraph tags)

**Comment by Vyvy-vi** [comment]
I think we can set these more custom metatags using [ssrtemplate](https://docusaurus.io/docs/docusaurus.config.js#ssrtemplate)

**Comment by luxumbra** [comment]
@Vyvy-vi an old PR was merged this week that sorts this out. However, I have not been able to add these tags AND make the preview display the hero/main image on any given page - either down to my own skill limitations or down to the limitations of Docusaurus. 

I'd say, if you can improve on what is already in place without a heap of work, go for it but we are wanting to put more energy and thought into building the MetaGame platform (MyMeta, MetaOS) than adding new functionality to the wiki in its current state. We will be migrating the wiki to a new platform later this year - quite possibly running a CMS like Sanity.io or Ghost and Gatsby/Next because we often find our desires for the wiki are hampered by the limitations of Docusaurus.

**Comment by Vyvy-vi** [comment]
I think that was mainly due to docosaurus' limitations, but I think we could maybe have that tweaked(I'll have to look through it), but considering that we might be migrating soon, perhaps this can wait, and be picked up when we re-build the wiki, and aren't limited

**Comment by luxumbra** [comment]
> I think that was mainly due to docosaurus' limitations, but I think we could maybe have that tweaked(I'll have to look through it), but considering that we might be migrating soon, perhaps this can wait, and be picked up when we re-build the wiki, and aren't limited

I guess we could have a simple metadata component that can be used on a page by page basis to override the settings in the `docusaurus.config.js` file. Title, description and `og:image` could be set as props maybe? I just don't think we can make it so the tags are handled automatically.
