### ISSUE TITLE
Playbooks not appearing as one of the categories in the editing GUI

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#253]
Wiki:
![image](https://user-images.githubusercontent.com/55857222/123556021-5d418b00-d789-11eb-9732-7df60d4040ea.png)

Edit mode:
![image](https://user-images.githubusercontent.com/55857222/123556010-561a7d00-d789-11eb-912d-2b7a7188230a.png)

**Comment by jonathanprozzi** [comment]
Taking a look at this now @peth-yursick

**Comment by jonathanprozzi** [comment]
Resolved the sidebars issue locally so going to dive into this now.

**Comment by jonathanprozzi** [comment]
I know what the issue is to resolve this but facing some issues with running the CMS in a local dev instance. Once I get that resolved I can continue working on this.

**Comment by jonathanprozzi** [comment]
Running NetlifyCMS locally with Docusaurus throws an error when navigating to `/admin` -- 

I've tested this out on our build and also on another NetlifyCMS/Docusaurus site and did some research on it. It says that there is a YAML error in the NetlifyCMS config, but I've run both tests in a YAML parser and our YAML is fine (also got this error with our current YAML on our working build).

I narrowed it down and it seems what's happening is that Docusaurus is attempting to apply a layout to the YAML file. I noticed someone else had this issue with NetlifyCMS and Docusaurus when running locally (it doesn't happen when the site is actually built -- just when in local dev)

With that said, I've added the playbooks to the UI, but I won't be able to see it until we deploy because the login redirects to the prod domain.

**Comment by jonathanprozzi** [comment]
I have this working on my own deployed clone of the wiki. I did that in order to test the config and make sure that it works:

![playbooks-cms-ui](https://user-images.githubusercontent.com/9438776/125211795-ef13c280-e276-11eb-8538-059c23412e14.jpg)
