### ISSUE TITLE
"Last updated"

### ISSUE THREAD

**Issue by peth-yursick** [MetaFam/metagame-wiki#256]
Would be great to have a "last updated" info on every wiki page, so it makes it easier to see if a page might be out of date & needs to get updated.
The next step would be to have some kind of a system for keeping track of pages who haven't been update in longer than X but let's get that one step at a time :)
"last updated" pls

**Comment by jonathanprozzi** [comment]
Hi @peth-yursick 

I took a look at this and I think I got it working. It uses git history for the author and the timestamp. 

The local build is using mock data so it doesn't have the correct time/date, but adding the config for this adds it to every page inside docs across from the 'Edit this...':

![last-updated-mock](https://user-images.githubusercontent.com/9438776/124067547-642a0100-da08-11eb-98cf-5e4486ed6543.jpg)

In order to test what this looks like with actual data I'll make a PR and we can look at the preview.

**Comment by luxumbra** [comment]
This looks good to me @jonathanprozzi 👍🏻

**Comment by jonathanprozzi** [comment]
Great! will make a PR -- sorry, was out of sorts the last few days.

**Comment by jonathanprozzi** [comment]
Opened a new PR https://github.com/MetaFam/metagame-wiki/pull/278 related to this

**Comment by jonathanprozzi** [comment]
I think we can close this now that the PR has been merged. 
@luxumbra
